spring.datasource.url: jdbc:h2:mem:bookDB

server:
  port: 8080
  servlet:
    context-path: /

# swagger
spring-doc:
  swagger-ui:
    path: /swagger
spring:

  security:

    user:
      password: 6624


